# Generated by Django 6.0.3 on 2026-03-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('environment', 'Environmental'), ('health', 'Health Camp'), ('social', 'Social Awareness'), ('special', 'Special Camp')], max_length=50)),
                ('date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='events/')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
